server:
  port: 9004

spring:
  application:
    name: distribute-auth-server
  redis:
    host: 175.24.40.52
    port: 6379
    database: 2
    password:
    timeout: 3000
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost02:9002/eureka/,http://localhost01:9001/eureka/
    instance:
      instance-id: distribute-auth-server
      prefer-ip-address: true
