server:
  port: 9011

mybatis:
  type-aliases-package: com.watermelon.api.entity
#  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
    # 在控制台显示 sql 语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  application:
    name: distribute-course-manage-provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/evaluation?serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: 105036
    type: com.alibaba.druid.pool.DruidDataSource

    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat,wall
    maxPoolPreparedStatementPerConnectionSize: 20
    connectionProperties: druid.stat.mergeSql=true

  #向admin-dashboard监控服务发送监控消息
  boot:
    admin:
      client:
        url: http://localhost:9005

#向dashboard监控服务提供监控端口
management:
   endpoints:
     web:
       exposure:
         #include: health,info,hystrix.stream
         include: "*"

#设置向Eureka进行服务注册
eureka:
  client:
    service-url:
      #当多个Eureka的hostname相同时，微服务默认向defaultZone的最后一个实例进行注册
      defaultZone: http://localhost02:9002/eureka/,http://localhost01:9001/eureka/
    #修改微服务名称application-id
    instance:
      instance-id: distribute-course-manage-provider-01

#swagger开关
switch-swagger-up: true