server:
  port: 9022

spring:
  redis:
    host: 175.24.40.52
    port: 6379
    database: 1
    password:

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost01:9001/eureka/,http://localhost02:9002/eureka/

#swagger开关
switch-swagger-up: true