server:
  port: 9021

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost01:9001/eureka/,http://localhost02:9002/eureka/

#swagger开关
switch-swagger-up: true